- name: Identify new hosts
  hosts: all
  gather_facts: yes
  vars:
    recent_timestamp: "{{ lookup('pipe', 'date +%s') | int }}" # replace with your cutoff epoch timestamp
  tasks:
    - name: Add to new hosts group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: new_hosts
      when: ansible_date_time.epoch | int > recent_timestamp | int